### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by mastercyb** [bro-n-bro/bro_rating#1]
I would allocate to cost efficiency of validator at least 50%. 

I like the idea to reduce rank as weight grow. 

Also I would completely remove voting as this could lead to automated voting which will harm.

**Comment by bro-n-bro-0** [comment]
Hi @mastercyb  and ty for your opinion!

We've published a new version of our rating, so looking forward to your review. 
Regarding your previous comments:

> I would allocate to cost efficiency of validator at least 50%.

We're on the way to getting justice weights for defined criteria

> Also I would completely remove voting as this could lead to automated voting which will harm.

We don't want to do that. One of the issues of cosmos ecosystem networks is a low proposals turnout. The voting criterion is set up with `points_weighed_by_max_available` calculation scheme and that means if all validators will complete this criterion the competition will be moved to other criteria. That is why we called that `base`.
